
BoxLayout:
    orientation: 'vertical'
    Button:
        text: "List Items"
        size_hint_x: 0.2
    Button:
        size_hint_x: 0.2
        text: "Hire Item"
    Button:
        size_hint_x: 0.2
        text: "Return Items"
    Button:
        size_hint_x: 0.2
        text: "Confirm"
    Button:
        size_hint_x: 0.2
        text: "Add New Item"
    BoxLayout:
        orientation: 'vertical'
        Button:
            size_hint_x: 0.8
            text:"testt"